<a href="https://colab.research.google.com/github/monarkparekh/MAE-598__Design-Optimization/blob/Assignment-3/MAE_598__Design_Optimization_HW3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<b><h1>MAE 598 Design Optimization: 
Assignment 3</h1></b>

Name: Monark Parekh <br> 
ASU ID: 1222179426


<h2><b> Question 1 <b></h2>

Importing the required libraries

In [256]:
from sympy import symbols, diff
import numpy as np
import matplotlib.pyplot as plt
#import math
from tabulate import tabulate
from sympy import exp


Defining the p1 and p2 saturation values

In [257]:
T = 20
a1, a2, a3 = 8.07131, 1730.63, 233.426
p1_sat = 10**(a1 - (a2/(T + a3)))
a1, a2, a3 = 7.43155 , 1554.679, 240.337
p2_sat = 10**(a1 - (a2/(T + a3)))

Defining the given data

In [258]:
data = [['x1','p'],[0,28.1], [0.1,34.4], [0.2,36.7], [0.3,36.9], [0.4,36.8], [0.5,36.7], [0.6,36.5], [0.7,35.4], [0.8,32.9], [0.9,27.7], [1,17.5]]
print(tabulate(data, headers='firstrow', tablefmt='fancy_grid'))

╒══════╤══════╕
│   x1 │    p │
╞══════╪══════╡
│  0   │ 28.1 │
├──────┼──────┤
│  0.1 │ 34.4 │
├──────┼──────┤
│  0.2 │ 36.7 │
├──────┼──────┤
│  0.3 │ 36.9 │
├──────┼──────┤
│  0.4 │ 36.8 │
├──────┼──────┤
│  0.5 │ 36.7 │
├──────┼──────┤
│  0.6 │ 36.5 │
├──────┼──────┤
│  0.7 │ 35.4 │
├──────┼──────┤
│  0.8 │ 32.9 │
├──────┼──────┤
│  0.9 │ 27.7 │
├──────┼──────┤
│  1   │ 17.5 │
╘══════╧══════╛


Determining the Gradient and Hessian of the given pressure function

In [259]:
A12, A21, x1, x2 = symbols('A12 A21 x1 x2', real=True)
f = (x1 * exp(A12 * ((A21*x2/(A12*x1 + A21*x2))**2)) * p1_sat) + (x2 * exp(A21 * ((A12*x1/(A12*x1 + A21*x2))**2)) * p2_sat)
grad = [0,0]
grad[0] = diff(f, A12)
grad[1] = diff(f, A21)
print(f'G1 = {grad[0]}\nG2 = {grad[1]}')
H1 = diff(grad[0], A12)
H2 = diff(grad[0], A21)
H3 = diff(grad[1], A12)
H4 = diff(grad[1], A21)
Hess = np.array([[H1,H2],[H3,H4]])
print(f'\nH1 = {H1}\nH2 = {H2}\nH3 = {H3}\nH4 = {H4}')
symbolsToDelete = ('A12', 'A21', 'x1', 'x2')
for z0 in symbolsToDelete:
    del globals()[z0]

G1 = 17.4732520845971*x1*(-2*A12*A21**2*x1*x2**2/(A12*x1 + A21*x2)**3 + A21**2*x2**2/(A12*x1 + A21*x2)**2)*exp(A12*A21**2*x2**2/(A12*x1 + A21*x2)**2) + 28.8240995274052*x2*(-2*A12**2*A21*x1**3/(A12*x1 + A21*x2)**3 + 2*A12*A21*x1**2/(A12*x1 + A21*x2)**2)*exp(A12**2*A21*x1**2/(A12*x1 + A21*x2)**2)
G2 = 17.4732520845971*x1*(-2*A12*A21**2*x2**3/(A12*x1 + A21*x2)**3 + 2*A12*A21*x2**2/(A12*x1 + A21*x2)**2)*exp(A12*A21**2*x2**2/(A12*x1 + A21*x2)**2) + 28.8240995274052*x2*(-2*A12**2*A21*x1**2*x2/(A12*x1 + A21*x2)**3 + A12**2*x1**2/(A12*x1 + A21*x2)**2)*exp(A12**2*A21*x1**2/(A12*x1 + A21*x2)**2)

H1 = 17.4732520845971*x1*(-2*A12*A21**2*x1*x2**2/(A12*x1 + A21*x2)**3 + A21**2*x2**2/(A12*x1 + A21*x2)**2)**2*exp(A12*A21**2*x2**2/(A12*x1 + A21*x2)**2) + 17.4732520845971*x1*(6*A12*A21**2*x1**2*x2**2/(A12*x1 + A21*x2)**4 - 4*A21**2*x1*x2**2/(A12*x1 + A21*x2)**3)*exp(A12*A21**2*x2**2/(A12*x1 + A21*x2)**2) + 28.8240995274052*x2*(-2*A12**2*A21*x1**3/(A12*x1 + A21*x2)**3 + 2*A12*A21*x1**2/(A12*x1 + A21*x2

Defining the given pressure function 'p'

In [260]:
def p(x1, A12, A21):
  x2 = 1 - x1
  T1 = x1 * math.exp(A12 * ((A21*x2/(A12*x1 + A21*x2))**2)) * p1_sat
  T2 = x2 * math.exp(A21 * ((A12*x1/(A12*x1 + A21*x2))**2)) * p2_sat
  function_value_p = T1 + T2
  G1 = 17.4732520845971*x1*(-2*A12*A21**2*x1*x2**2/(A12*x1 + A21*x2)**3 + A21**2*x2**2/(A12*x1 + A21*x2)**2)*exp(A12*A21**2*x2**2/(A12*x1 + A21*x2)**2) + 28.8240995274052*x2*(-2*A12**2*A21*x1**3/(A12*x1 + A21*x2)**3 + 2*A12*A21*x1**2/(A12*x1 + A21*x2)**2)*exp(A12**2*A21*x1**2/(A12*x1 + A21*x2)**2) 
  G2 = 17.4732520845971*x1*(-2*A12*A21**2*x2**3/(A12*x1 + A21*x2)**3 + 2*A12*A21*x2**2/(A12*x1 + A21*x2)**2)*exp(A12*A21**2*x2**2/(A12*x1 + A21*x2)**2) + 28.8240995274052*x2*(-2*A12**2*A21*x1**2*x2/(A12*x1 + A21*x2)**3 + A12**2*x1**2/(A12*x1 + A21*x2)**2)*exp(A12**2*A21*x1**2/(A12*x1 + A21*x2)**2)
  gradient = np.array([[G1, G2],])

  H1 = 17.4732520845971*x1*(-2*A12*A21**2*x1*x2**2/(A12*x1 + A21*x2)**3 + A21**2*x2**2/(A12*x1 + A21*x2)**2)**2*exp(A12*A21**2*x2**2/(A12*x1 + A21*x2)**2) + 17.4732520845971*x1*(6*A12*A21**2*x1**2*x2**2/(A12*x1 + A21*x2)**4 - 4*A21**2*x1*x2**2/(A12*x1 + A21*x2)**3)*exp(A12*A21**2*x2**2/(A12*x1 + A21*x2)**2) + 28.8240995274052*x2*(-2*A12**2*A21*x1**3/(A12*x1 + A21*x2)**3 + 2*A12*A21*x1**2/(A12*x1 + A21*x2)**2)**2*exp(A12**2*A21*x1**2/(A12*x1 + A21*x2)**2) + 28.8240995274052*x2*(6*A12**2*A21*x1**4/(A12*x1 + A21*x2)**4 - 8*A12*A21*x1**3/(A12*x1 + A21*x2)**3 + 2*A21*x1**2/(A12*x1 + A21*x2)**2)*exp(A12**2*A21*x1**2/(A12*x1 + A21*x2)**2)
  H2 = 17.4732520845971*x1*(-2*A12*A21**2*x2**3/(A12*x1 + A21*x2)**3 + 2*A12*A21*x2**2/(A12*x1 + A21*x2)**2)*(-2*A12*A21**2*x1*x2**2/(A12*x1 + A21*x2)**3 + A21**2*x2**2/(A12*x1 + A21*x2)**2)*exp(A12*A21**2*x2**2/(A12*x1 + A21*x2)**2) + 17.4732520845971*x1*(6*A12*A21**2*x1*x2**3/(A12*x1 + A21*x2)**4 - 4*A12*A21*x1*x2**2/(A12*x1 + A21*x2)**3 - 2*A21**2*x2**3/(A12*x1 + A21*x2)**3 + 2*A21*x2**2/(A12*x1 + A21*x2)**2)*exp(A12*A21**2*x2**2/(A12*x1 + A21*x2)**2) + 28.8240995274052*x2*(-2*A12**2*A21*x1**3/(A12*x1 + A21*x2)**3 + 2*A12*A21*x1**2/(A12*x1 + A21*x2)**2)*(-2*A12**2*A21*x1**2*x2/(A12*x1 + A21*x2)**3 + A12**2*x1**2/(A12*x1 + A21*x2)**2)*exp(A12**2*A21*x1**2/(A12*x1 + A21*x2)**2) + 28.8240995274052*x2*(6*A12**2*A21*x1**3*x2/(A12*x1 + A21*x2)**4 - 2*A12**2*x1**3/(A12*x1 + A21*x2)**3 - 4*A12*A21*x1**2*x2/(A12*x1 + A21*x2)**3 + 2*A12*x1**2/(A12*x1 + A21*x2)**2)*exp(A12**2*A21*x1**2/(A12*x1 + A21*x2)**2)
  H3 = 17.4732520845971*x1*(-2*A12*A21**2*x2**3/(A12*x1 + A21*x2)**3 + 2*A12*A21*x2**2/(A12*x1 + A21*x2)**2)*(-2*A12*A21**2*x1*x2**2/(A12*x1 + A21*x2)**3 + A21**2*x2**2/(A12*x1 + A21*x2)**2)*exp(A12*A21**2*x2**2/(A12*x1 + A21*x2)**2) + 17.4732520845971*x1*(6*A12*A21**2*x1*x2**3/(A12*x1 + A21*x2)**4 - 4*A12*A21*x1*x2**2/(A12*x1 + A21*x2)**3 - 2*A21**2*x2**3/(A12*x1 + A21*x2)**3 + 2*A21*x2**2/(A12*x1 + A21*x2)**2)*exp(A12*A21**2*x2**2/(A12*x1 + A21*x2)**2) + 28.8240995274052*x2*(-2*A12**2*A21*x1**3/(A12*x1 + A21*x2)**3 + 2*A12*A21*x1**2/(A12*x1 + A21*x2)**2)*(-2*A12**2*A21*x1**2*x2/(A12*x1 + A21*x2)**3 + A12**2*x1**2/(A12*x1 + A21*x2)**2)*exp(A12**2*A21*x1**2/(A12*x1 + A21*x2)**2) + 28.8240995274052*x2*(6*A12**2*A21*x1**3*x2/(A12*x1 + A21*x2)**4 - 2*A12**2*x1**3/(A12*x1 + A21*x2)**3 - 4*A12*A21*x1**2*x2/(A12*x1 + A21*x2)**3 + 2*A12*x1**2/(A12*x1 + A21*x2)**2)*exp(A12**2*A21*x1**2/(A12*x1 + A21*x2)**2)
  H4 = 17.4732520845971*x1*(-2*A12*A21**2*x2**3/(A12*x1 + A21*x2)**3 + 2*A12*A21*x2**2/(A12*x1 + A21*x2)**2)**2*exp(A12*A21**2*x2**2/(A12*x1 + A21*x2)**2) + 17.4732520845971*x1*(6*A12*A21**2*x2**4/(A12*x1 + A21*x2)**4 - 8*A12*A21*x2**3/(A12*x1 + A21*x2)**3 + 2*A12*x2**2/(A12*x1 + A21*x2)**2)*exp(A12*A21**2*x2**2/(A12*x1 + A21*x2)**2) + 28.8240995274052*x2*(-2*A12**2*A21*x1**2*x2/(A12*x1 + A21*x2)**3 + A12**2*x1**2/(A12*x1 + A21*x2)**2)**2*exp(A12**2*A21*x1**2/(A12*x1 + A21*x2)**2) + 28.8240995274052*x2*(6*A12**2*A21*x1**2*x2**2/(A12*x1 + A21*x2)**4 - 4*A12**2*x1**2*x2/(A12*x1 + A21*x2)**3)*exp(A12**2*A21*x1**2/(A12*x1 + A21*x2)**2)
  Hessian = np.array([[H1,H2],[H3,H4]])
  return function_value_p, gradient, Hessian

Defining the given Objective Function

In [263]:
def objective_function(data, A12, A21):
  objective_value = 0
  objective_gradient = 0
  objective_Hessian = 0
  for i in range(1,12):
    temp1,temp2,temp3 = p(data[i][0],A12, A21)
    objective_value = objective_value + ((data[i][1] - temp1)**2)
    objective_gradient = objective_gradient + (2*(data[i][1] - temp1)*(temp2))
    objective_Hessian = objective_Hessian + 2*((np.matmul(np.transpose(temp2),temp2))+((data[i][1] - temp1) * temp3))
  return objective_value, objective_gradient, objective_Hessian

In [262]:
gradient = objective_function(data, 1, 1)[1]
Hessian = objective_function(data, 1, 1)[2]
#gradient = gradient.astype(float)
print(gradient)
print(Hessian)
np.matmul(gradient.astype(float),np.linalg.inv(Hessian.astype(float)))

[[426.807072133291 355.789431385797]]
[[15.5194022615079 582.099305446930]
 [582.099305446930 -52.4002127146531]]


array([[0.67560034, 0.71520814]])

# <b>Newton's Algorithm</b>

In [293]:
def newtonsalgorithm(x0,maximum_iteration):
  epsilon = (10)**-6
  A = []
  error_values = []
  gradient_normal = []
  A.append(x0)
  for k in range(0,maximum_iteration):
      obj_p, gradient, Hessian = objective_function(data,A[k][0],A[k][1])
      gradient_normal.append(np.linalg.norm(gradient.astype(float)))
      error_values.append(obj_p)
      if gradient_normal[k] <= epsilon:
        print(f'\nThe Newtons Algorithm has converged to a point in {k} iterations\n')
        print(f'Current Gradient Normal is {gradient_normal[k]}\n[A12, A21] = {A[k]}')
        return A,gradient_normal,(k),error_values
      
      new_A = A[k] - np.matmul(gradient.astype(float),np.linalg.inv(Hessian.astype(float)))
      A.append([new_A[0][0],new_A[0][1]])

      if k == (maximum_iteration - 1):
        print(f"Number of iterations has exceeded the maxinimum iterations, still not converged to the given threshold.\nCurrent Gradient Normal is {gradient_normal[k]}\nCurrent point is {A[k]}")
        return A,gradient_normal,(k),error_values

In [295]:
x0 = np.array([1,1])
maximum_iteration = 100
A,gradient_normal,(k),error_values = newtonsalgorithm(x0,maximum_iteration)
print(A[k])


The Newtons Algorithm has converged to a point in 28 iterations

Current Gradient Normal is 3.858301632592024e-07
[A12, A21] = [-1790.2069105372896, -1783.1812306223917]
[-1790.2069105372896, -1783.1812306223917]


<h2><b> Question 2 <b></h2>

Importing the required libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import math

Defining the Objective function

In [ ]:
def objective_function(x1, x2):
  return (((4 - 2.1*(x1**2) + ((x1**4)/3))*(x1**2)) + (x1*x2) + ((-4 + 4*(x2**2))*(x2**2)))